

===   [ 收集测试用例 ]  === 


== cases\__st__.py 


== cases\班级管理.py 


** no cases in this file , skip it.

== cases\一年级1班无老师\__st__.py 


== cases\一年级1班无老师\学生测试.py 


** no cases in this file , skip it.

== cases\一年级1班无老师\班级测试.py 


** no cases in this file , skip it.

== cases\一年级1班无老师\老师测试.py 


** no cases in this file , skip it.

== cases\一年级1班无老师\一个数学老师无学生\__st__.py 


== cases\一年级1班无老师\一个数学老师无学生\学生测试.py 


** no cases in this file , skip it.

== cases\一年级1班无老师\一个数学老师无学生\有学生\__st__.py 


== cases\一年级1班无老师\一个数学老师无学生\有学生\学生测试.py 


** no cases in this file , skip it.

== cases\一年级1班无老师\一年级2班无老师无学生\__st__.py 


== cases\一年级1班无老师\一年级2班无老师无学生\班级修改.py 


== cases\一年级1班无老师\一年级2班无老师无学生\两个班级一个数学老师\__st__.py 


== cases\一年级1班无老师\一年级2班无老师无学生\两个班级一个数学老师\老师测试2.py 


** no cases in this file , skip it.

== cases\一年级1班无老师\无老师有学生\__st__.py 


== cases\一年级1班无老师\无老师有学生\老师发布测试.py 


** no cases in this file , skip it.

== cases\一年级1班无老师\无老师有学生\老师登录.py 


** no cases in this file , skip it.


===   [ 执行测试用例 ]  === 

预备执行用例数量 : 1



  ========= 测试开始 : 20250305_151959 =========



>>> cases\

[ suite setup ] cases\


>>> cases\一年级1班无老师\

[ suite setup ] cases\一年级1班无老师\


>>> cases\一年级1班无老师\一年级2班无老师无学生\

[ suite setup ] cases\一年级1班无老师\一年级2班无老师无学生\


>>> cases\一年级1班无老师\一年级2班无老师无学生\班级修改.py

* 修改班级2 - tc000052  -  2025-03-05 15:19:59

  [ case execution steps ]

-- 第 1 步 -- 修改一个班级，使班级名为一个重名的新的名字 

{'reason': '未知错误:Traceback (most recent call last):\n  File "/home/yjyx/yijiao_src/yijiao_main/services/datamodel/schoolclass/models.py", line 612, in modifyClass\n    school_class.save()\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save\n    force_update=force_update, update_fields=update_fields)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 803, in _save_table\n    forced_update)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 853, in _do_update\n    return filtered._update(values) > 0\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update\n    return query.get_compiler(self.db).execute_sql(CURSOR)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql\n    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql\n    cursor.execute(sql, params)\n  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute\n    return self.cursor.execute(sql, params)\n  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute\n    return self.cursor.execute(sql, params)\n  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute\n    return self.cursor.execute(query, args)\n  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute\n    self.errorhandler(self, exc, value)\n  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nIntegrityError: (1062, "Duplicate entry \'\\xe7\\x99\\xbd\\xe6\\x9c\\x88\\xe9\\xbb\\x91\\xe7\\xbe\\xbd1\\xe7\\x8f\\xad-407-1\' for key \'name\'")\n', 'retcode': 10000}

** 检查点 **  添加结果检查 ---->  !! 不通过!!

  FAIL    
Traceback:
    ~~~~~~~~~~~~~~^^
  File "D:\Program Files\Python313\Practice\PythonProject2\cases\一年级1班无老师\一年级2班无老师无学生\班级修改.py", line 67, in teststeps
    CHECK_POINT('添加结果检查',
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
                retAlter['retcode'] == 1 and retAlter['reason'] == "duplicated class name")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python313\Practice\PythonProject2\.venv\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError


[ suite teardown ] cases\一年级1班无老师\一年级2班无老师无学生\

[ suite teardown ] cases\一年级1班无老师\


  ========= 测试结束 : 20250305_151959 =========


  耗时    : 0.302 秒


  预备执行用例数量 : 1

  实际执行用例数量 : 1

  通过 : 0

  失败 : 1

  异常 : 0

  套件初始化失败 : 0

  套件清除  失败 : 0

  用例初始化失败 : 0

  用例清除  失败 : 0
